# Generated by Django 3.2 on 2021-05-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_rename_color_colores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colores',
            new_name='Colore',
        ),
    ]
