# Generated by Django 3.2 on 2021-05-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_equipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='modelo_id',
            new_name='modelo',
        ),
    ]
