# Generated by Django 3.2 on 2021-05-07 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_equipo', '0002_rename_modelo_id_equipo_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='estado_id',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='laboratorio_id',
            new_name='laboratorio',
        ),
    ]
